"""
================================================================================
VERSION 2.0 REQUIREMENTS & ADVERSARIAL VERIFICATION SUITE
================================================================================
Comprehensive test suite testing Version 2.0 deliverables:
  - Instagram_Chat_Analysis_Amina_Hamid_v2.html
  - v2.html
Derived strictly from ORIGINAL_REQUEST.md (## 2026-09-17T11:23:00Z) and PROJECT_V2.md.

Covers:
  1. Exact byte identity between primary and replica files.
  2. Standalone single-file validity (zero broken local script/style imports).
  3. Accurate rendering of all 18,589 chat metrics.
  4. Zero <audio> tags and zero audio players (peaceful silence).
  5. Zero occurrences of 'swt' (strictly 'Allah Ta'ala').
  6. Zero prohibited version words in romantic user copy.
  7. Hidden Husband Edit Mode, secret triple-tap (03072026), private dashboard modal (#husband-dashboard-modal).
  8. Permanent quiz answer lock in localStorage and WhatsApp score sharing button.
  9. Two Cities One Heart card, 5 polaroid photos with touch lightbox & Prev/Next, ambient rose petals toggle (🌸).
 10. Love Quiz 2.0 structure (5 questions with distributed answers B, D, A, C, B).
================================================================================
"""

import hashlib
import os
import re
import unittest
from tests import spec_oracle_v2 as oracle_v2


class BaseV2TestCase(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        cls.v2_primary_path = os.path.join(cls.project_root, oracle_v2.V2_PRIMARY_FILE)
        cls.v2_replica_path = os.path.join(cls.project_root, oracle_v2.V2_REPLICA_FILE)
        cls.v2_exists = os.path.exists(cls.v2_primary_path)

        cls.v2_content = ""
        if cls.v2_exists:
            with open(cls.v2_primary_path, "r", encoding="utf-8", errors="ignore") as f:
                cls.v2_content = f.read()

    def require_v2_file(self):
        """Skip test gracefully if V2 application file is not yet generated by implementer."""
        if not self.v2_exists:
            self.skipTest(
                f"V2 file '{oracle_v2.V2_PRIMARY_FILE}' not yet generated (pending M2_IMPL)."
            )


# ==============================================================================
# 1. SPECIFICATION ORACLE & MATHEMATICAL CONTRACTS
# ==============================================================================
class TestV2SpecOracleContracts(unittest.TestCase):
    """Verify mathematical properties and data integrity of the V2 dataset."""

    def test_v2_total_message_count_math(self):
        """Verify total messages equals sum of Hamid and Amina messages."""
        m = oracle_v2.CHAT_METRICS_V2
        self.assertEqual(m['total_messages'], 18589)
        self.assertEqual(m['hamid_messages'], 9301)
        self.assertEqual(m['amina_messages'], 9288)
        self.assertEqual(m['hamid_messages'] + m['amina_messages'], m['total_messages'])

    def test_v2_partner_balance_percentages(self):
        """Verify 50.03% vs 49.97% partner balance with 13-message delta."""
        m = oracle_v2.CHAT_METRICS_V2
        hamid_pct = round((m['hamid_messages'] / m['total_messages']) * 100, 2)
        amina_pct = round((m['amina_messages'] / m['total_messages']) * 100, 2)
        self.assertEqual(hamid_pct, 50.03)
        self.assertEqual(amina_pct, 49.97)
        self.assertEqual(m['hamid_messages'] - m['amina_messages'], 13)

    def test_v2_monthly_progression_math(self):
        """Verify monthly message totals and daily averages."""
        monthly = oracle_v2.CHAT_METRICS_V2['monthly_progression']
        self.assertEqual(monthly['july']['total'], 2610)
        self.assertEqual(monthly['august']['total'], 10489)
        self.assertEqual(monthly['september']['total'], 5490)
        total = monthly['july']['total'] + monthly['august']['total'] + monthly['september']['total']
        self.assertEqual(total, 18589)

        # Verify daily velocities
        self.assertAlmostEqual(monthly['july']['daily_avg'], 113.5, places=1)
        self.assertAlmostEqual(monthly['august']['daily_avg'], 338.4, places=1)
        self.assertAlmostEqual(monthly['september']['daily_avg'], 366.0, places=1)

    def test_v2_peak_day_contract(self):
        """Verify peak day date and volume (Mon 17 Aug with 857 msgs)."""
        peak = oracle_v2.CHAT_METRICS_V2['peak_day']
        self.assertEqual(peak['total'], 857)
        self.assertEqual(peak['hamid'], 457)
        self.assertEqual(peak['amina'], 400)
        self.assertEqual(peak['hamid'] + peak['amina'], 857)
        self.assertIn("17 August 2026", peak['day_str'])

    def test_v2_midnight_intimacy_math(self):
        """Verify midnight window (8,730 msgs) and peak hour (00:00-01:00 with 3,762 msgs)."""
        mid = oracle_v2.CHAT_METRICS_V2['midnight_chats']
        self.assertEqual(mid['total'], 8730)
        self.assertEqual(mid['peak_hour_count'], 3762)
        self.assertAlmostEqual(mid['percentage'], 46.96, places=2)
        self.assertEqual(mid['hamid_count'] + mid['amina_count'], 8730)

    def test_v2_reaction_leaderboard_math(self):
        """Verify total reactions (3,368), Amina Queen (2,604 / 77.3%), top emojis (👍 1,569, ❤️ 667)."""
        rxn = oracle_v2.CHAT_METRICS_V2['reactions']
        self.assertEqual(rxn['total'], 3368)
        self.assertEqual(rxn['amina_count'], 2604)
        self.assertEqual(rxn['hamid_count'], 764)
        self.assertEqual(rxn['amina_count'] + rxn['hamid_count'], 3368)
        self.assertAlmostEqual(rxn['amina_pct'], 77.32, places=1)
        self.assertEqual(rxn['top_emojis']['👍'], 1569)
        self.assertEqual(rxn['top_emojis']['❤️'], 667)

    def test_v2_sweet_words_counts(self):
        """Verify sweet words frequencies (yaad 96, love 48, jaan 40, pyaar 39)."""
        sw = oracle_v2.CHAT_METRICS_V2['sweet_words']
        self.assertEqual(sw['yaad'], 96)
        self.assertEqual(sw['love'], 48)
        self.assertEqual(sw['jaan'], 40)
        self.assertEqual(sw['pyaar'], 39)

    def test_v2_longest_break_contract(self):
        """Verify longest break duration 47.94h and flight message."""
        lb = oracle_v2.CHAT_METRICS_V2['longest_break']
        self.assertEqual(lb['duration_hours'], 47.94)
        self.assertEqual(lb['broken_by'], 'Amina Chamadiya')
        self.assertIn('flight', lb['message_text'].lower())

    def test_v2_love_quiz_answer_distribution(self):
        """Verify Love Quiz 2.0 non-predictable answer distribution (B, D, A, C, B)."""
        q = oracle_v2.LOVE_QUIZ_2_CONTRACT
        self.assertEqual(q['total_questions'], 5)
        self.assertEqual(q['distribution'], ['B', 'D', 'A', 'C', 'B'])
        self.assertEqual(q['correct_indices'], [1, 3, 0, 2, 1])
        # Verify not all Option A (anti-predictability guard)
        self.assertNotEqual(q['distribution'], ['A', 'A', 'A', 'A', 'A'])
        # Verify unique correct options include at least 4 distinct letters
        self.assertGreaterEqual(len(set(q['distribution'])), 4)


# ==============================================================================
# 2. FILE INDEPENDENCE & BYTE IDENTITY
# ==============================================================================
class TestV2FileIntegrity(BaseV2TestCase):
    """Verify file presence and exact byte identity between v2 primary and replica."""

    def test_v2_primary_file_exists(self):
        """Verify Instagram_Chat_Analysis_Amina_Hamid_v2.html exists."""
        self.require_v2_file()
        self.assertTrue(os.path.isfile(self.v2_primary_path))

    def test_v2_replica_file_exists(self):
        """Verify v2.html exists in project root."""
        self.require_v2_file()
        self.assertTrue(os.path.isfile(self.v2_replica_path))

    def test_v2_files_byte_for_byte_identical(self):
        """Verify Instagram_Chat_Analysis_Amina_Hamid_v2.html and v2.html are 100% byte identical."""
        self.require_v2_file()
        with open(self.v2_primary_path, "rb") as f1, open(self.v2_replica_path, "rb") as f2:
            bytes1 = f1.read()
            bytes2 = f2.read()
        self.assertEqual(len(bytes1), len(bytes2), "File sizes differ between V2 primary and replica")
        self.assertEqual(bytes1, bytes2, "Content differs between V2 primary and replica")

    def test_v2_standalone_validity_no_broken_local_imports(self):
        """Verify standalone single-file validity with zero broken local script/style imports."""
        self.require_v2_file()
        clean, violations = oracle_v2.StandaloneValidatorV2.audit_standalone(self.v2_content)
        self.assertTrue(clean, f"Broken local imports found in V2: {violations}")


# ==============================================================================
# 3. CHAT METRICS RENDERING FIDELITY
# ==============================================================================
class TestV2ChatMetricsRendering(BaseV2TestCase):
    """Verify that all 18,589 chat metrics are rendered accurately in V2."""

    def test_v2_total_messages_18589_rendered(self):
        """Verify 18,589 total message count is present."""
        self.require_v2_file()
        self.assertTrue(
            "18,589" in self.v2_content or "18589" in self.v2_content,
            "V2 must render 18,589 total messages"
        )

    def test_v2_partner_balance_counts_rendered(self):
        """Verify Hamid (9,301) and Amina (9,288) counts are rendered."""
        self.require_v2_file()
        self.assertTrue("9,301" in self.v2_content or "9301" in self.v2_content, "Missing Hamid 9,301 count")
        self.assertTrue("9,288" in self.v2_content or "9288" in self.v2_content, "Missing Amina 9,288 count")

    def test_v2_monthly_progression_rendered(self):
        """Verify monthly message counts and velocities for July, Aug, and Sept."""
        self.require_v2_file()
        # July (2,610 / 113.5)
        self.assertTrue("2,610" in self.v2_content or "2610" in self.v2_content or "113.5" in self.v2_content)
        # August (10,489 / 338.4)
        self.assertTrue("10,489" in self.v2_content or "10489" in self.v2_content or "338.4" in self.v2_content)
        # September (5,490 / 366.0)
        self.assertTrue("5,490" in self.v2_content or "5490" in self.v2_content or "366.0" in self.v2_content or "366" in self.v2_content)

    def test_v2_peak_day_aug17_rendered(self):
        """Verify peak day Mon 17 Aug with 857 msgs is rendered."""
        self.require_v2_file()
        self.assertIn("857", self.v2_content, "V2 must render peak day count 857")
        self.assertTrue("17 August" in self.v2_content or "Aug 17" in self.v2_content, "V2 must reference August 17")

    def test_v2_midnight_chats_rendered(self):
        """Verify 8,730 total midnight messages and 3,762 peak hour messages are rendered."""
        self.require_v2_file()
        self.assertTrue("8,730" in self.v2_content or "8730" in self.v2_content, "Missing midnight 8,730 msgs")
        self.assertTrue("3,762" in self.v2_content or "3762" in self.v2_content, "Missing peak hour 3,762 msgs")

    def test_v2_reactions_leaderboard_rendered(self):
        """Verify 3,368 reactions, Amina 2,604 (Reaction Queen), and top emojis 👍 (1,569), ❤️ (667)."""
        self.require_v2_file()
        self.assertTrue("3,368" in self.v2_content or "3368" in self.v2_content, "Missing 3,368 reactions count")
        self.assertTrue("2,604" in self.v2_content or "2604" in self.v2_content, "Missing Amina 2,604 reactions count")
        self.assertTrue("1,569" in self.v2_content or "1569" in self.v2_content, "Missing 👍 1,569 count")
        self.assertIn("667", self.v2_content, "Missing ❤️ 667 count")

    def test_v2_sweet_words_rendered(self):
        """Verify sweet words frequencies: yaad (96), love (48), jaan (40), pyaar (39)."""
        self.require_v2_file()
        self.assertIn("96", self.v2_content, "Missing yaad 96 count")
        self.assertIn("48", self.v2_content, "Missing love 48 count")
        self.assertIn("40", self.v2_content, "Missing jaan 40 count")
        self.assertIn("39", self.v2_content, "Missing pyaar 39 count")

    def test_v2_longest_break_rendered(self):
        """Verify 47.94h longest break and Amina's flight message."""
        self.require_v2_file()
        self.assertIn("47.94", self.v2_content, "Missing 47.94 hours break")
        self.assertTrue("flight" in self.v2_content.lower(), "Missing flight message reference")


# ==============================================================================
# 4. ZERO AUDIO & PEACEFUL SILENCE GUARANTEE
# ==============================================================================
class TestV2ZeroAudioPolicy(BaseV2TestCase):
    """Verify pure peaceful romantic silence (0 audio tags, 0 audio players)."""

    def test_v2_zero_audio_tags(self):
        """Assert zero <audio> elements in V2 HTML."""
        self.require_v2_file()
        audio_tags = re.findall(r'<audio\b[^>]*>', self.v2_content, re.IGNORECASE)
        self.assertEqual(len(audio_tags), 0, f"Found <audio> tags in V2: {audio_tags}")

    def test_v2_zero_audio_player_controls(self):
        """Assert zero audio players, audio sources, or audio controls in V2 HTML."""
        self.require_v2_file()
        clean, violations = oracle_v2.AudioSilenceValidatorV2.audit_silence(self.v2_content)
        self.assertTrue(clean, f"Audio violations detected in V2: {violations}")


# ==============================================================================
# 5. STRICT ISLAMIC REVERENCE (ALLAH TA'ALA ONLY, ZERO SWT)
# ==============================================================================
class TestV2IslamicReverence(BaseV2TestCase):
    """Verify exclusive and reverent usage of Allah Ta'ala and zero abbreviations."""

    def test_v2_zero_swt_occurrences(self):
        """Assert zero occurrences of 'swt' or '(swt)' in V2."""
        self.require_v2_file()
        swt_matches = re.findall(r'\bswt\b|\(swt\)', self.v2_content, re.IGNORECASE)
        self.assertEqual(len(swt_matches), 0, f"Found prohibited 'swt' abbreviation: {swt_matches}")

    def test_v2_strictly_uses_allah_taala(self):
        """Assert presence of reverent 'Allah Ta'ala' in V2 copy."""
        self.require_v2_file()
        clean, violations = oracle_v2.IslamicNamingValidatorV2.audit_islamic_naming(self.v2_content)
        self.assertTrue(clean, f"Islamic naming violations in V2: {violations}")


# ==============================================================================
# 6. ZERO PROHIBITED VERSION WORDS IN USER COPY
# ==============================================================================
class TestV2ZeroProhibitedWords(BaseV2TestCase):
    """Verify absence of technical version labels, build hashes, and debug labels."""

    def test_v2_no_prohibited_version_words_in_user_copy(self):
        """Assert no 'v1.0', 'beta', 'debug mode', '(NEW ANALYTICS)' in visible user text."""
        self.require_v2_file()
        # Strip script and style blocks before checking user-visible copy
        body_copy = re.sub(r'<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>', '', self.v2_content, flags=re.IGNORECASE)
        body_copy = re.sub(r'<style\b[^<]*(?:(?!<\/style>)<[^<]*)*<\/style>', '', body_copy, flags=re.IGNORECASE)
        body_copy = re.sub(r'<!--.*?-->', '', body_copy, flags=re.DOTALL)

        violations = oracle_v2.ZeroVersionValidatorV2.scan(body_copy)
        self.assertEqual(
            len(violations),
            0,
            f"Found prohibited version or debug words in user-visible copy: {violations}"
        )


# ==============================================================================
# 7. HIDDEN HUSBAND EDIT MODE & SECURITY
# ==============================================================================
class TestV2HusbandModeSecurity(BaseV2TestCase):
    """Verify Hidden Husband Edit Mode, secret triple-tap (03072026), and private dashboard."""

    def test_v2_husband_dashboard_modal_exists(self):
        """Verify presence of #husband-dashboard-modal."""
        self.require_v2_file()
        self.assertTrue(
            'id="husband-dashboard-modal"' in self.v2_content or "id='husband-dashboard-modal'" in self.v2_content,
            "V2 must include #husband-dashboard-modal"
        )

    def test_v2_husband_passcode_03072026_configured(self):
        """Verify secret passcode 03072026 is configured in V2."""
        self.require_v2_file()
        self.assertIn("03072026", self.v2_content, "V2 must configure default passcode 03072026")

    def test_v2_husband_triple_tap_timeout(self):
        """Verify secret triple tap timeout window (1500ms or 1.5s)."""
        self.require_v2_file()
        self.assertTrue(
            "1500" in self.v2_content or "triple" in self.v2_content.lower(),
            "V2 must handle secret triple tap gesture"
        )


# ==============================================================================
# 8. PERMANENT QUIZ ANSWER LOCK & WHATSAPP SHARING
# ==============================================================================
class TestV2QuizAnswerLockAndSharing(BaseV2TestCase):
    """Verify localStorage answer persistence and WhatsApp score sharing link."""

    def test_v2_permanent_quiz_storage_lock(self):
        """Verify quiz results are permanently stored in localStorage."""
        self.require_v2_file()
        self.assertTrue(
            "localStorage" in self.v2_content and "quiz" in self.v2_content.lower(),
            "V2 must persist quiz answers to localStorage to prevent retries/undo"
        )

    def test_v2_whatsapp_sharing_button_present(self):
        """Verify WhatsApp score share button and deep-link generation."""
        self.require_v2_file()
        self.assertTrue(
            "wa.me" in self.v2_content or "whatsapp" in self.v2_content.lower(),
            "V2 must provide WhatsApp score sharing button"
        )


# ==============================================================================
# 9. VISUAL & INTERACTIVE COMPONENTS (TWO CITIES, POLAROIDS, PETALS)
# ==============================================================================
class TestV2VisualComponents(BaseV2TestCase):
    """Verify Two Cities card, 5 polaroids lightbox with Prev/Next, and floating rose petals."""

    def test_v2_two_cities_card_present(self):
        """Verify 'Two Cities, One Heart' connection card (Surat ⟷ Bhiwandi)."""
        self.require_v2_file()
        self.assertTrue(
            "Surat" in self.v2_content and "Bhiwandi" in self.v2_content,
            "V2 must include Surat and Bhiwandi in connection card"
        )
        self.assertTrue(
            "two-cities-card" in self.v2_content or "Two Cities" in self.v2_content,
            "V2 must include Two Cities card structure"
        )

    def test_v2_polaroid_showcase_and_touch_lightbox(self):
        """Verify 5 polaroids, lightbox modal, and Prev/Next buttons."""
        self.require_v2_file()
        # Lightbox modal
        self.assertTrue(
            "photo-lightbox-modal" in self.v2_content or "lightbox" in self.v2_content.lower(),
            "V2 must include photo lightbox modal"
        )
        # Prev / Next navigation
        self.assertTrue(
            "prev" in self.v2_content.lower() and "next" in self.v2_content.lower(),
            "V2 lightbox must include Previous and Next navigation"
        )

    def test_v2_ambient_rose_petals_toggle(self):
        """Verify floating rose petals container and 🌸 toggle button."""
        self.require_v2_file()
        self.assertIn("🌸", self.v2_content, "V2 must provide floating rose petals toggle button (🌸)")
        self.assertTrue(
            "ambient-rose-petals" in self.v2_content or "petal" in self.v2_content.lower(),
            "V2 must include ambient rose petals animation container"
        )


# ==============================================================================
# 10. LOVE QUIZ 2.0 STRUCTURE & DISTRIBUTION
# ==============================================================================
class TestV2LoveQuiz2Structure(BaseV2TestCase):
    """Verify Love Quiz 2.0 challenging questions and non-predictable answer distribution."""

    def test_v2_quiz_questions_structure(self):
        """Verify 5 questions reflecting extended dataset in V2."""
        self.require_v2_file()
        # Icebreaker "suno"
        self.assertIn("suno", self.v2_content.lower(), "Quiz must reference icebreaker 'suno'")
        # Peak day 857
        self.assertIn("857", self.v2_content, "Quiz must reference peak day 857 messages")
        # Reaction Queen / top emoji 👍
        self.assertTrue(
            "👍" in self.v2_content or "1569" in self.v2_content or "1,569" in self.v2_content,
            "Quiz must reference top reaction emoji 👍"
        )


if __name__ == "__main__":
    unittest.main()
